# Generated by Django 3.0.5 on 2020-05-05 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20200505_1505'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vinylmodel',
            old_name='last_name',
            new_name='album_name',
        ),
        migrations.RenameField(
            model_name='vinylmodel',
            old_name='name',
            new_name='artist',
        ),
        migrations.AddField(
            model_name='vinylmodel',
            name='song_name',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
